### ISSUE TITLE
Easier inclusion of custom statements into ceph.conf

### ISSUE THREAD

**Issue by l-mb** [SUSE/DeepSea#205]
The default ceph.conf.j2 only includes files for configured RGW instances.

A naïve user might modify the file directly to adjust/include additional settings, but that'd be overwritten by the next package update. (And also confuse rpm -V.)

A more savvy user might instead add a custom file to configuration_init: in global.yml, using our ceph.conf.j2 as a template. However, that'd mean they'd have to manually merge any further updates we provide to that file.

A really savvy user would instead set up a custom file, but include ours via a j2 macro directive, which is not part of our default template though.

I don't think this is user-friendly enough and most likely, users will get this wrong. Users also should not have to any macro code to just include a single "a = b" statement.

We need to make it easier to include custom snippets - simply including all files under ceph.conf.d/ in numbered sequence (similar to udev.d etc) would do it. The ceph.conf.j2 file should include a comment to document that it is read-only and should not be changed by customers. (Maybe even ship it 0400 only.)

**Comment by swiftgist** [comment]
I've been wanting to do this for a while, but wasn't sure how to handle customizations to subsections.  But something is definitely needed.

Having a /srv/salt/ceph/configuration/files/ceph.conf.d should work well and seem obvious enough.  I think we can rely on a Jinja include here since it's more forgiving about absent files.  

Not sure about extrapolating this to all other configuration files, but I think I favor this strategy over creating more entries in the Salt pillar.
