### ISSUE TITLE
postgres remains after openATTIC uninstall

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#237]
If openATTIC is removed from a node (i.e. removed from policy.cfg, rerun stages 2-5), the postgres database is left running.

I think the default behavior should at least stop and disable the service if not uninstall it.  As far as other services sharing the postgres database and wanting this behavior, I'll suggest that the /srv/salt/ceph/rescind/openattic/default.sls is renamed to default-postgres.sls or something similar.  That makes the reconfiguration one variable away.

I'm looking for feedback on this one.

**Comment by l-mb** [comment]
I think that assuming that by default we're the only user of the postgres instance we installed makes sense.

(However, wiping the database might require one more confirmation - users have the habit of reinstalling stuff when confronted with weird errors, and maybe they then don't expect that all their preference data goes away.)

If one wanted to be excessively smart, one could default to testing for tables we didn't create in Postgres. But I'm perfectly fine with that being left as a future exercise if anyone ever complains ;-)

(In the future, if/when we containerize, the point is moot since we simply would have our own postgres instance inside our container anyway.)

**Comment by votdev** [comment]
For your information, there is already a configuration option in the oA pillar data to enable or disable dropping the database, please see https://github.com/SUSE/DeepSea/blob/master/srv/pillar/ceph/openattic.sls-example.

**Comment by swiftgist** [comment]
Shouldn't that be the default then?  Move the contents into the global.yml via populate?

**Comment by votdev** [comment]
This is an example config file, the default is set to [False](https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/rescind/openattic/default.sls#L14).

**Comment by swiftgist** [comment]
Doesn't this mean that a default DeepSea deployment where an admin moves openATTIC from one node to another will leave apache2, icinga and postgres running? 

 I think I can go along with leaving the database there by default.  Since the admin may have made a simple mistake at initial deployment or may have been running oA for six months, both are indistinguishable.

Why would I want to leave running services on by default though?

**Comment by sebastian-philipp** [comment]
I'm not sure about zypper, but `apt-get` has a command `autoremove` which automatically removes dependencies which are no longer needed. On Debian based systems, `apt-get autoremove` would remove Postgres or Apache, if there is no other package that requires the package. I would be OK with calling  `autoremove` after uninstalling oA.

**Comment by swiftgist** [comment]
Migrated to a different strategy with #500.  The option to drop the database is there, but the default only stops postgres.
