### ISSUE TITLE
Default timeout for stage.3

### ISSUE THREAD

**Issue by capri1989** [SUSE/DeepSea#261]
Hi,

I would like to have a timeout for stage.3.

e.g.: I tried to deploy a cluster with DeepSea but I've done a misconfiguration of my OSD nodes. In this case Stage.3 gets stuck forever and waits until the Ceph Cluster is Healthy. From an administrator perspective their was no useful log output or something else so I could have been aware of that. I would prefer to be able to specify a default timeout for this stage.

Your thoughts?

**Comment by jschmid1** [comment]
> In this case Stage.3 gets stuck forever and waits until the Ceph Cluster is Healthy.
That's not the case, iirc. 

The way salt works, prevents us from globally assign timeouts to our so-called 'stages'

Stages are 'orchestration' files which then again call states, which call modules(mostly). So that'd require to handle timeouts in each module (most of the custom modules have that - built-in modules also). If a timeout is reached, salt can abort the orchestration if the stanza that received the timeout, has a `failhard=True` flag.

Would you mind to run, while executing stage.3?

`salt-run state.event pretty=True` 

and see which command hangs?

**Comment by swiftgist** [comment]
@capri1989 I suspect something did not fail properly and continued on until some command such as creating Ceph pools hangs indefinitely.  

This is one of the reasons we added the validations of the environment.  We may need more.

There's also `salt-run jobs.active` to help track down a hung job.

**Comment by capri1989** [comment]
I'll try to reproduce it and give you the output

**Comment by capri1989** [comment]
The timeout of the "Check if the cluster is healthy" is reached but deepsea didn't kill the stuck command "rbd -p rbd ls". This causes this behavior.
@rjfd Will create a PR for that to fix the validator. 

The quick fix we did was -> 

elif self.in_dev_env and len(storage) < 1:
            msg = "Too few storage nodes {}".format(",".join(storage))
            self.errors['storage'] = [ msg ]

**Comment by jschmid1** [comment]
great! closed
