### ISSUE TITLE
nettest does not take ceph.conf into account

### ISSUE THREAD

**Issue by l-mb** [SUSE/DeepSea#30]
As far as I can see, nettest ignores which networks Ceph is actually using. I think it should take that into account.

It should try whether all Ceph member nodes with addresses on the public_network are accessible from all nodes. It should also try to contact to all cluster network addresses from all nodes that need to be able to access them (OSDs, MONs, MDS, ...) For this, it should also set the source address properly to the local address on that network.

Right now, I think nettest leverages all IPv4 addresses, even those that Ceph doesn't use. I don't think we should try that.

**Comment by oms4suse** [comment]
Question : do we expect this test to run only after deepsea has run stage 3 successfully?

**Comment by oms4suse** [comment]
I am very keen to reduce the combinatorial explosion with ipv4 addresses. So advice guidance here would be very useful.

**Comment by oms4suse** [comment]
We could also use traceroute, this would highlight any issues and is easy to implement. 

This might help also diagnose other issues?

**Comment by swiftgist** [comment]
I believe this issue is addressed now.  The default command will try all addresses in the Salt cluster.  When a cluster name is supplied, only the public and cluster networks are used.  For example,

salt-run net.ping
salt-run net.ping ceph OR salt-run net.ping cluster=ceph

However, there may be addresses that an admin wishes to exclude such as those dedicated to gateways.  Add an exclude parameter with or without the Salt modifiers and the related minions or addresses will be removed from the list.  For example, 

salt-run net.ping exclude=igw2.ceph
salt-run net.ping exclude=L@igw2.ceph

salt-run net.ping exclude=192.168.21.6
salt-run net.ping exclude=S@192.168.21.6

salt-run net.ping exclude=192.168.21.0/28
salt-run net.ping exclude=S@192.168.21.0/28

And both parameters can be specified in multiple ways.

salt-run net.ping cluster=ceph exclude=mon2.ceph,mon3.ceph
salt-run net.ping ceph mon2.ceph,mon3.ceph
salt-run net.ping ceph L@mon2.ceph,mon3.ceph
