### ISSUE TITLE
[qa] Create a stripped down version of stage.0

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#368]
After trying the newly added qa/suites/basic/* suites on my vagrant setup, I think we might need a stripped down/small version of stage.0

### Reason
(Under the premise you haven't updated your base image in a while)
1) If you quickly want to bootstrap a cluster and programmatically execute i.e. 'health-ok.sh', the master will be updated/rebooted, hence 'heath-ok.sh' will be interrupted. 

2) The update process, ofc depending on the state of your base image, will take up most of the time and will hinder you from testing more frequently during development.

3) Updating from the already added SUSE repos will also update 'DeepSea', which makes testing an older version a pain.

### What should be removed
 * `ceph.updates.restart`
* `ceph.updates`

Thoughts?

**Comment by smithfarm** [comment]
I thought about not running stage 0 in the test, since it breaks every time a kernel update is released (Salt reboots the VMs and that's the end of the test).

But after some thought I decided against it, because running a different version of one of the stages reduces test coverage. I deploy my OVH images automatically, so redeploying them for each kernel update is not a problem.

**Comment by smithfarm** [comment]
I don't mind having this in DeepSea, but I would object to its use in the DeepSea integration suite. Better to put our efforts into making it easy to have always up-to-date images, vagrant boxes, etc.

**Comment by jschmid1** [comment]
> But after some thought I decided against it, because running a different version of one of the stages reduces test coverage.

If you always have an up-to-date base image you will only test a certain amount of the code anyways, i.e. never execute the underlying module. We wouldn't loose too much there.

**Comment by jschmid1** [comment]
> I don't mind having this in DeepSea, but I would object to its use in the DeepSea integration suite. Better to put our efforts into making it easy to have always up-to-date images, vagrant boxes, etc.

Would be the cleaner solution. That's something we should pursue regardless.

**Comment by jan--f** [comment]
Another way to deal with this is to make sure the kernel packages are in a good state before starting the test. For vagrant this can be part of the provisioning.

**Comment by jschmid1** [comment]
> Another way to deal with this is to make sure the kernel packages are in a good state before starting the test. For vagrant this can be part of the provisioning.

good point. 

Without making a debate on principles of this, I'd like to raise the general need for a switch to disable updates and reboots ( i.e. in a SUMA controlled env )

**Comment by smithfarm** [comment]
> If you always have an up-to-date base image you will only test a certain amount of the code anyways, i.e. never execute the underlying module.

This is true, but we could come up with a way of testing through reboots. I.e. the reboot does not necessarily need to fail the test. Upstream has powercycle tests, for example.

**Comment by smithfarm** [comment]
Bottom line is I would be disappointed if the tests had to use something other than "stage.0" because there's no guarantee that this "something other" will share any code at all with "stage.0"

I know it would share code *now*, but code can drift over time and we could lose coverage.

**Comment by swiftgist** [comment]
We've always needed an alternate default for Stage 0.  One annoyance is that Salt fights us on this a bit.  Ideally, we could separate the master and minion into different sls files and include what we need in each.  The issue is that we cannot use more than one include statement per sls file and any Jinja loops/conditionals have side effects.

In the meantime, we can create three additional default-something files for the top level, master and minion.  Copy from the default.sls and modify accordingly.

**Comment by jschmid1** [comment]
closed via #419
