### ISSUE TITLE
ceph.remove.mds is probably broken

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#400]
srv/salt/ceph/remove/mds/default.sls includes:

````
fail mds:
  cmd.run:
    - name: "ceph mds fail 0"
````

That will fail the MDS with id 0, except in real life the MDS (or MDSes) will have $(hostname) as their ID. Shouldn't this do `ceph mds fail $(hostname)` for each MDS?

**Comment by jan--f** [comment]
The code has changed since and works for mds removal. Its sufficient to just stop the service...provided the cluster config can be fulfilled (max_mds, ...).
ceph mds fail is more of a cluster management command and we shouldn't need to use this in salt.
So closing...feel free to reopen if I have missed details.
