### ISSUE TITLE
DeepSea creates pools with hardcoded number of PGs, causing non-trivial clusters to come up in HEALTH_WARN due to insufficient PGs per OSD

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#536]
As we have discussed before, DeepSea wants to be helpful and create pools for the user, so the user has something working from the get-go. This has been tested on small clusters, and seems to be useful.

The problem is that, when creating a pool, DeepSea must specify a number of PGs.

When a human user creates a pool, they are advised to calculate the number of PGs, taking into account their cluster topology, CRUSH map, and anticipated usage patterns. Contrast this with DeepSea, which does no calculation at all and simply hardcodes the number of PGs.

Since the number of PGs is hardcoded, it is trivial to make DeepSea bring up the cluster in HEALTH_WARN (due to insufficient PGs per OSD) simply by adding OSDs.

This is reproducible in all cases where DeepSea is currently creating pools on behalf of the user.

There are several possibilities for addressing this:

1. fudge by increasing the hardcoded number of PGs, in the hopes that fewer users will get bitten
2. document that the cluster might come up in HEALTH_WARN, so users know they need to re-do the pool creation
3. do some kind of calculation instead of hard-coding the number of PGs, but this means DS has to keep track of which pools are already created since all the pools will presumably be created over all the OSDs
4. leave it to the user to create pools

Options 1 and 2 strike me as unprofessional, and the calculation in 3 seems like it's bound to come up with the wrong value. If we did go with 3, we still need to document which pools DS creates and explain to users how to fix things if the number of PGs guessed by DeepSea turns out to be wrong for their cluster.

As for option "4", well . . . Ceph was auto-creating a pool and stopped doing that, presumably for the same reasons. Also, I heard that ceph-ansible does not create pools, either.

It's as if DS is assuming the user is a Ceph neophyte who knows very little about Ceph and simply wants to push buttons. The current behavior works for this type of user because they're unlikely to have more than a few OSDs. However, it risks annoying users who have knowledge of Ceph, because they will have to re-do the pools when DS is finished, but then if they ever re-run Stage 4 the pools will get re-created . . . (?)

**Comment by smithfarm** [comment]
Users for whom the hard-coded PG values are not right could pre-create the pools (which DS would otherwise create) before running Stage 4. So there is a sane option for dealing with this issue.

The expert user could also elect to not assign the roles (mds, igw, rgw, etc.) that trigger pool creation, and deploy these services manually. But this might cause issues with openATTIC functionality relating to these services, right? For example, if I don't assign the "igw" role to any node, but instead deploy iSCSI manually, will the oA iSCSI features still work?

**Comment by Martin-Weiss** [comment]
Keep in mind that in most deployments it is also required to adjust the crushmap after stage.3 / before any pool gets created (split data-centers / racks etc.. and create new rules).

It would be great to have a single, central place of options / variables in DS where an admin could adjust the things that DS is going to create - list of pools (names, pgs, rule to be used, application to be assigned, erasure or replicated...).

**Comment by rjfd** [comment]
@smithfarm 
> For example, if I don't assign the "igw" role to any node, but instead deploy iSCSI manually, will the oA iSCSI features still work?

Nope, oA will not be able to manage iSCSI in that situation.

**Comment by jan--f** [comment]
The pg_num for the auto created pools was chosen so that things would "just work"™ after running a stage. As you say @smithfarm, a manual step after stage 3 gives an admin control over the pools. The alternative is to not have a mountable CephFS instance after stage 4 (unless some other manual intervention happens during the deploy stage). The current implementation was deemed to be the most desirable given its low complexity.

As for have DS read a list of pool specifications, the question is when an admin has to write those specs, it seems overkill for DS to basically put a ``` ceph osd pool create $specs``` before this spec. a simple, say shell script would be just as effective, not add any serious complexity and  it would be reusable over many deployments. We try to avoid pulling things into DS that are of the "call a command" variety (if they are not required for later orchestration steps of course).

**Comment by smithfarm** [comment]
> The pg_num for the auto created pools was chosen so that things would "just work"™ after running a stage.

Things only "just work" if you have few enough OSDs to dodge the HEALTH_WARN, though.

What is the plan for dealing with this? Just wait for the users to trip over it?

**Comment by smithfarm** [comment]
> oA will not be able to manage iSCSI in that situation.

So, users with more than "x" OSDs (where "x" is a small number less than 50) must maintain an 'iscsi-images' pool for as long as they intend to use openATTIC to manage iSCSI.

**Comment by smithfarm** [comment]
> The current implementation was deemed to be the most desirable given its low complexity.

In what way would DeepSea be more complex if it didn't create pools?

**Comment by smithfarm** [comment]
DS does not have the power to reduce the complexity of Ceph itself. Pools have to be managed by the users/admins.

**Comment by jan--f** [comment]
> Things only "just work" if you have few enough OSDs to dodge the HEALTH_WARN, though. Also, the number of OSDs needed to hit the HEALTH_WARN is not very large - less than 50 I believe.

There would still be mountable CephFS instance. As I said, the alternative would be to not have that, since there is no reliable way to get the pg_num just right. That does seem to just move the manual intervention somewhere else.
I'm not averse to this per se, I just don't see the benefit.

**Comment by smithfarm** [comment]
The benefit is greater transparency. Users with more than a few OSDs get jolted immediately, so they will know about it, but users of low-OSD clusters (admittedly a majority at the moment) get lulled into a false sense of security that DS is managing the pools it creates.

**Comment by swiftgist** [comment]
I consider the other scenario to be a more awkward support situation.  I pushed the button for iSCSI or CephFS and I get nothing.  I am not exactly sure how that should impress anyone just wanting to learn about Ceph.

At least with the HEALTH_WARN,  a diligent admin will see that something is up.  Also, it shows that the process worked although the settings for their hardware is not ideal.  That's worth something and shouldn't be dismissed.

I would argue that we should prioritize the accurate calculation and crush map editing rather than make all things manual.

Now, if this is causing an issue in testing or where some prefer a clean slate, we can create an alternate default for both CephFS and iSCSI.  If an admin chooses to get nothing when pressing a button, then nobody is surprised.

**Comment by smithfarm** [comment]
Testing is not an issue - I can add the required kludge to the large cluster test cases.

Feel free to close this if you don't agree with my arguments.

**Comment by smithfarm** [comment]
> I would argue that we should prioritize the accurate calculation and crush map editing rather than make all things manual.

First, the proposal is not to make "all things" manual, but to make pool creation manual.

Second, the two courses of action are not mutually exclusive - you *could* remove the pool creation now and add it back in later when the enabling features are done. (But if you don't agree that the pool creation in its current form is fundamentally flawed, then you're probably not going to do that.)

**Comment by swiftgist** [comment]
No, because breaking Stage 4 does not make things inherently better.  If you demand that users stop and configure things by hand, then there's little point in anything automated.  You may think I am splitting hairs between pool creation and all things, but those that benefit from the current automation will not see a difference.  

We can also keep things working now and inform the users what the HEALTH_WARN is since that will always be an ongoing issue for any Ceph administrator.

**Comment by smithfarm** [comment]
Question answered, CI kludge added.
