### ISSUE TITLE
Allow role separation of Deepsea/Salt Master role

### ISSUE THREAD

**Issue by neilashbysenior** [SUSE/DeepSea#576]
Is it possible to allow the Ceph admin role to be separate from the Deepsea machine and Salt master server?
My understanding is that the Ceph admin role must be on a server directly on the Ceph front end network.

I would like the Deepsea role and Salt master function to be on a machine not directly connected to the Ceph network but instead carry out their functions over a routed network (management network). This means I can place The Deepsea and Salt Master roles on a server behind a firewall in our management infrastructure, which gives a centralised server. It also means I can collocate Suse Manager so that there is only one Salt Master server.

This would be a much better solution for scaling, security and ease of management.
Thanks,
Neil.

**Comment by swiftgist** [comment]
Not at the moment.  The problem is that managing Ceph from a minion on the public network is only half of the requirement.  The other is updating the Salt master itself.  Many steps in the orchestration that run a command on the minion of the master update files in /srv/pillar/ceph or /srv/salt/ceph.  All of these steps would need to be decoupled and make the complexity increase a bit.  

Consider something as simple as the bootstrap keyring.  The file is generated on the Salt master and could be propagated via the management network with the normal "file.managed" functionality.  The other half of the step is to add the keyring to Ceph itself.  Instead of calling the `ceph auth add ...` command from the Salt master, we need to call it from the _admin_ minion.  Technically not too difficult, but the extra hop does mean that an admin would need to be logged into two machines to debug any task.

Now, consider the reverse.  The runner ui_rgw.py supports the API to openATTIC.  This runner communicates directly from the Salt master to a RadosGW minion over the public network.  With no public network access, this logic needs to be broken up into a runner and a module.  That should work, but the side effect is that every call for anything ui related has an extra hop adding to the latency.

The reason to go down this path at all is for managing the Ceph cluster and its services.  Another solution would be having these services available on the management network in addition to the public network.  We would still have a central point of administration.  (I have considered experimenting with netcat just to see what is possible.)

**Comment by neilashbysenior** [comment]
Hi Eric, thanks for that. Understand what you are saying.

I've spoken a fair bit with Darren about this and our idea of having centralised management so as we scale and add more racks the bill of material is identical with each rack and management is truly central. At the moment we'll have to have the management in the storage racks due to the issues mentioned. Plus it means it'll probably be bare metal rather than a VM.

I guess Darren can keep me up to date on the roadmap for this and we will have to implement as I described.

 As for the dual Salt Master issue, I am waiting for a response from Suse about how to use two Suse products to provide a complete end to end lifecycle solution for storage. I think it is important to recognise that using both Suse Manager (and SMT) and Suse Enterprise Storage makes sense for customers and therefore it makes sense to ensure the dual Salt architecture is either documented or replaced with a single master.
Cheers,
Neil.
