### ISSUE TITLE
ceph.migrate.policy should add the openattic role to the master node

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/DeepSea#751]
When installing SES 4, DeepSea will create an installation of openATTIC on the master node.

When following the updates steps for SES 4 to SES 5, when executing `ceph.migrate.policy`, should add the `openattic` role to the master node, in order enable the stage 4 to fix the settings file of openattic.

**Comment by swiftgist** [comment]
Due to some manual openATTIC installations, adding the role will not be the only change necessary.  

Considering that openATTIC dashboard is now part of Ceph itself, the standalone openATTIC will be winding down and the role removed from DeepSea in the future.  With that in mind, we would not be extending this part of the automation.  The manual effort is minimal and only necessary once.
